### ISSUE TITLE
scroll restoration do not revert to same position

### ISSUE THREAD

**Issue by admondtamang** [nanyang24/react-scroll-restoration#1]

**Comment by admondtamang** [comment]
When data load from the server the scroll miss matches scroll position.

**Comment by nanyang24** [comment]
> When data load from the server the scroll miss matches scroll position.

@admondtamang  Thx for the report.

Given that this example may be quite specific, I would like to see a specific demo that I can easily troubleshoot.

Of course, you can mention PR to fix your example, I'm more than willing to review the code.

I'll reopen this issue.

**Comment by admondtamang** [comment]
https://drive.google.com/file/d/1181ildYupVh0yC-yFDghTo6fK_V2C68u/view?usp=sharing

**Comment by admondtamang** [comment]
https://user-images.githubusercontent.com/22430270/103070908-a8b48a00-45ea-11eb-935c-20e5949ed362.mp4

**Comment by nanyang24** [comment]
I probably understand, I'll try to fix it.

Merry Christmas🎄

**Comment by nanyang24** [comment]
https://github.com/nanyang24/react-scroll-restoration/issues/2#issuecomment-852725868
