### ISSUE TITLE
Scroll restore before data loads in

### ISSUE THREAD

**Issue by dominik-myszkowski** [nanyang24/react-scroll-restoration#2]
The scroll restore happens immediately after page has been shifted to previous one, not allowing the data to load on page (and not allowing to scroll yet). It would be nice to expose some kind of method which will be used once the data has been loaded and that would trigger the scroll to correct position.
For example my shop has a list of products provided by GraphQL query. When user clicks on a product a new page loads with product details. When user swiches back to the list the products load again from graphQL and only then (graphql query onComplete) can I scroll back to correct position.

**Comment by nanyang24** [comment]
Thank you for your advice, I will find the best way to solve it.
Please look forward to it.

**Comment by nanyang24** [comment]
After a series of studies, I will answer this question


Scroll Restoration is to restore the scroll position to the last time you left when navigating to the previously visited page.

But for the regular client-side rendering of data fetching, this seems to be contrary.

Here I suggest using some solution that caches the query results and renders them synchronously with the cached results on re-rendering.

- [react-query](https://react-query.tanstack.com/)
- [swr](https://swr.vercel.app/)
