### ISSUE TITLE
Incorrect peer dependency 'react-router-dom@^4.0.0'

### ISSUE THREAD

**Issue by ekabolotina** [nanyang24/react-scroll-restoration#9]
Hello! Thank you for supporting such a great library. My project is using React Router v5, so I get a warning like this
```react-scroll-restoration@1.0.8" has incorrect peer dependency "react-router-dom@^4.0.0"```

As [described in README](https://github.com/nanyang24/react-scroll-restoration#react-scroll-restoration) this library works with both v4 and v5, so it would be okay to set peer dependency like below:
```"react-router-dom": "^4.0.0 || ^5.0.0"```

**Comment by nanyang24** [comment]
🙇‍♂️ Hi Иван, thank you for the report! And for providing the solution, I will release the latest version in the next few days, let's look forward to it.

**Comment by SakisTsalk** [comment]
any updates on this?

**Comment by nanyang24** [comment]
fixed in https://github.com/nanyang24/react-scroll-restoration/releases/tag/v1.0.10

@ekabolotina @SakisTsalk @samybob1 you guys could update it to [1.0.10](https://www.npmjs.com/package/react-scroll-restoration/v/1.0.10) version pls and feel free to reach me if you have any questions.

**Comment by ekabolotina** [comment]
@nanyang24 hello! There is a trouble with v1.0.9 since there is no `dist` folder inside `node_modules/react-scroll-restoration`.

**Comment by nanyang24** [comment]
> @nanyang24 hello! There is a trouble with v1.0.9 since there is no `dist` folder inside `node_modules/react-scroll-
restoration`.


sry about that I thought the publishing tool would help check this case.
Pls check out the [1.0.10](https://www.npmjs.com/package/react-scroll-restoration/v/1.0.10) version again 🙇‍♂️
